"""Initial migration

Revision ID: 95488b29e767
Revises: 
Create Date: 2025-04-22 14:48:31.429240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95488b29e767'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_classrooms_id', table_name='classrooms')
    op.drop_index('ix_classrooms_name', table_name='classrooms')
    op.drop_table('classrooms')
    op.drop_table('classroom')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classroom',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('semester', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='classroom_pkey')
    )
    op.create_table('classrooms',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('semester', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='classrooms_pkey')
    )
    op.create_index('ix_classrooms_name', 'classrooms', ['name'], unique=True)
    op.create_index('ix_classrooms_id', 'classrooms', ['id'], unique=False)
    # ### end Alembic commands ###
